#' The application server-side
#'
#' @param input,output,session Internal parameters for {shiny}.
#'     DO NOT REMOVE.
#' @import shiny
#' @noRd
app_server <- function(input, output, session) {

  results_list <- list(
    student = get_golem_options("student_result"),
    course = get_golem_options("course_result"),
    student_course = get_golem_options("student_course_result"),
    buildings = get_golem_options("building_result"),
    rooms = get_golem_options("room_result")
  )
  app_data <- get_app_data(results_list) # a list with elements generated by `get_stats_tables()`

  # Home tab
  mod_value_boxes_server("home_smry", app_data$home$five_stats)
  output$home_summary_table <- render_gt(
    format_summary_table(app_data$home$error_summary)
  )

  # Summary tabs
  mod_smry_tab_server("student_smry", app_data$student, file = "student")
  mod_smry_tab_server("courses_smry", app_data$course, file = "course")
  mod_smry_tab_server("student_courses_smry", app_data$student_course, file = "student_course")
  mod_smry_tab_server("faculty_workload_smry", app_data$student, file = "student")
  mod_smry_tab_server("building_smry", app_data$building, file = "building")
  mod_smry_tab_server("room_smry", app_data$room, file = "room") # TODO

}
