#' The application server-side
#'
#' @param input,output,session Internal parameters for {shiny}.
#'     DO NOT REMOVE.
#' @import shiny
#' @noRd
app_server <- function(input, output, session) {

  data_in <- load_data_in() # a list with elements generated by `get_stats_tables()`

  # Home tab
  mod_value_boxes_server("home_smry", data_in$home$five_stats)
  output$home_summary_table <- renderTable(
    home_stats_tables$error_summary
  )

  # Summary tabs
  mod_smry_tab_server("student_smry", data_in$student)
  mod_smry_tab_server("courses_smry", data_in$course)
  mod_smry_tab_server("student_courses_smry", data_in$student_course)
  mod_smry_tab_server("faculty_workload_smry", data_in$student) # TODO

}
